# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ayamsuwir

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Log in to Azure using GitHub secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4343874690843F695CA05E742012159 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5A9A586E0B745DF9213181335A6E13A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA3E3833268C41B7BBAEF7F0305E0AE9 }}

      # Set environment variables in Azure, using the resource group secret
      - name: Set environment variables in Azure
        run: |
          az webapp config appsettings set --name ayamsuwir --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
            MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            MYSQL_USER=${{ secrets.MYSQL_USER }} \
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            MYSQL_DB=${{ secrets.MYSQL_DB }} \
            FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ayamsuwir'
          slot-name: 'Production'
